version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          context:
            - GITHUB
            - NPM
          filters:
            branches:
              only:
                - master
                - main
jobs:
  build:
    working_directory: ~/package
    machine:
      image: ubuntu-2204:2025.09.1
    steps:
      - checkout
      - run:
          name: Test Package
          environment:
            AWS_REGION: eu-west-1
            AWS_ACCESS_KEY_ID: test
            AWS_SECRET_ACCESS_KEY: test
          command: |
            docker compose -f docker-compose-test.yml up -d
            yarn
            yarn test
  deploy:
    working_directory: ~/package
    machine:
      image: ubuntu-2204:2025.09.1
    steps:
      - checkout
      - run:
          name: Deploy Package
          command: |
            export GH_TOKEN=$GITHUB_AUTH_TOKEN
            yarn
            yarn release
